Add publish script and cleanup

diff --git a/scripts/extract-links b/scripts/extract-links
--- a/scripts/extract-links
+++ b/scripts/extract-links
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 set -eEuo pipefail
 
 die() {
@@ -8,7 +8,7 @@ die() {
     exit "$_ret"
 }
 
-trap 'die "Error (exit $?): ${BASH_SOURCE[0]}:${LINENO} in ${FUNCNAME[1]:-main}" $?' ERR
+trap 'die "Error (exit $?): ${BASH_SOURCE[1]}:${BASH_LINENO[0]} in ${FUNCNAME[1]:-main}" $?' ERR
 
 print_help() {
     cat <<'USAGE'
@@ -71,10 +71,6 @@ parse_commandline() {
             _arg_web_images="on"
             ;;
         -h | --help)
-            print_help
-            exit 0
-            ;;
-        -h*)
             print_help
             exit 0
             ;;
diff --git a/scripts/frontmatter-parser b/scripts/frontmatter-parser
--- a/scripts/frontmatter-parser
+++ b/scripts/frontmatter-parser
@@ -32,22 +32,14 @@ Example:
 USAGE
 }
 
-err() {
-    local error_code
-    local error_line
-    error_code="${1:-}"
-    error_line="${2:-}"
-    if [[ -n "$error_code" && -n "$error_line" ]]; then
-        echo "Error: Script exited with code $error_code at line $error_line." >&2
-    elif [[ -n "$error_code" ]]; then
-        echo "Error: Script exited with code $error_code." >&2
-    else
-        echo "Error: An unknown error occurred." >&2
-    fi
-    exit "${error_code:-1}"
+die() {
+    local _ret="${2:-1}"
+    [[ "${_PRINT_HELP:-no}" == "yes" ]] && print_help >&2
+    printf '%s\n' "$1" >&2
+    exit "$_ret"
 }
 
-trap 'err $? $LINENO' ERR
+trap 'die "Error (exit $?): ${BASH_SOURCE[1]}:${BASH_LINENO[0]} in ${FUNCNAME[1]:-main}" $?' ERR
 
 # -- prerequisites check --
 
diff --git a/scripts/get-files-to-publish b/scripts/get-files-to-publish
--- a/scripts/get-files-to-publish
+++ b/scripts/get-files-to-publish
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 set -eEuo pipefail
 
 # Arguments parsing automatically generated by Argbash (https://argbash.dev)
@@ -10,7 +10,7 @@ die() {
     exit "$_ret"
 }
 
-trap 'die "Error (exit $?): ${BASH_SOURCE[0]}:${LINENO[0]} in ${FUNCNAME[1]-main}" $?' ERR
+trap 'die "Error (exit $?): ${BASH_SOURCE[1]}:${BASH_LINENO[0]} in ${FUNCNAME[1]-main}" $?' ERR
 
 begins_with_short_option() {
     case "${1:0:1}" in
@@ -92,10 +92,6 @@ parse_commandline() {
             validate_missing_alias "$_arg_missing_alias"
             ;;
         -h | --help)
-            print_help
-            exit 0
-            ;;
-        -h*)
             print_help
             exit 0
             ;;
