Create justfile

diff --git a/scripts/publish-site b/scripts/publish-site
--- a/scripts/publish-site
+++ b/scripts/publish-site
@@ -133,8 +133,8 @@ validate_arguments() {
 }
 
 resolve_directories() {
-    _src="$(realpath -m -- "$_arg_source_directory")" || die "Cannot resolve source." 2
-    _out="$(realpath -m -- "$_arg_output_directory")" || die "Cannot resolve output." 2
+    _src="$(realpath "$_arg_source_directory")" || die "Cannot resolve source." 2
+    _out="$(realpath "$_arg_output_directory")" || die "Cannot resolve output." 2
 }
 
 # -- publish site --
@@ -144,7 +144,7 @@ clean_output_directory() {
     fi
 
     local _home
-    _home="$(realpath -m -- "$HOME")"
+    _home="$(realpath "$HOME")"
     # Security check to prevent accidental deletion of important directories
     case "$_out" in
         /|""|"."|".."|"/root"|"/home"|"/usr"|"/etc"|"/var"|"$_home"|"$_home/."|"$_home/..")
@@ -204,9 +204,9 @@ get_clean_relative_path_list() {
         [[ -z "$_file" ]] && continue # skip empty
 
         if [[ "$_file" != /* ]]; then
-            _file="$(realpath -m -- "$_src/${_file#./}")" || continue
+            _file="$(realpath "$_src/${_file#./}")" || continue
         else
-            _file="$(realpath -m -- "$_file")" || continue
+            _file="$(realpath "$_file")" || continue
         fi
 
         if [[ "$_file" != "$_src/"* ]]; then
@@ -218,7 +218,7 @@ get_clean_relative_path_list() {
         fi
         _relative="${_file#"$_src"/}" # make relative to source
 
-        [[ -n "${_seen["$_relative"]+x}" ]] && continue # skip duplicates
+        [[ -n "${_seen["$_relative"]+_}" ]] && continue # skip duplicates
         _seen["$_relative"]=1
 
         _relative_files+=("$_relative")
@@ -235,7 +235,7 @@ get_files_and_images_to_copy() {
     if ! _files=$(get-files-to-publish "${_default_publish_args[@]}" "$_src"); then
         die "Failed to get files to publish." 4
     fi
-    readarray -d '' -t _files_to_copy <<<"$(_files)"
+    readarray -d '' -t _files_to_copy <<<"$_files"
     readarray -d '' -t _files_to_copy < <(_FAIL_ON_INVALID=yes get_clean_relative_path_list "${_files_to_copy[@]}")
 
     local -a _images_to_copy=()
